

CREATE TABLE MODEL (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(80) NOT NULL,
    SERIAL_NUMBER VARCHAR(80) NOT NULL,
    COLOR VARCHAR(80) NOT NULL,
    SIZE VARCHAR(80) NOT NULL,
    COST DECIMAL(10, 2) NOT NULL,
    TECHNOLOGY VARCHAR(80) NOT NULL,
    PRESENCE VARCHAR(80) NOT NULL,
    TYPE_PROCESSOR VARCHAR(80),
    REMEMBER VARCHAR(80),
    COUNT_CAMERAS INT,
    COUNT_DOORS INT,
    COUNT_MODES INT,
    COUNT_DUST_COLLECTOR INT,
    TYPE_COMPRESSOR VARCHAR(80),
    TECHNIC_ID  INT NOT NULL,
    CONSTRAINT TECHNIC_FOREIGN_KEY FOREIGN KEY (TECHNIC_ID) REFERENCES TECHNIC (ID)

);

CREATE TABLE TECHNIC (
                        ID BIGSERIAL NOT NULL PRIMARY KEY,
                        TITLE VARCHAR(80) NOT NULL,
                        MANUFACTURE_COUNTRY VARCHAR(80) NOT NULL,
                        MANUFACTURE VARCHAR(80) NOT NULL,
                        ORDER_ON VARCHAR(80) NOT NULL,
                        CREDIT VARCHAR(80) NOT NULL,
                        TYPE_TECHNIC VARCHAR(80) NOT NULL
);

CREATE TABLE TYPE_TECHNIC (
                         ID BIGSERIAL NOT NULL PRIMARY KEY,
                         TITLE VARCHAR(80) NOT NULL
);

ALTER TABLE MODEL
    ADD COLUMN TYPE_PROCESSOR VARCHAR(80),
    ADD COLUMN REMEMBER VARCHAR(80),
    ADD COLUMN COUNT_CAMERAS INT,
    ADD COLUMN COUNT_DOORS INT,
    ADD COLUMN COUNT_MODES INT,
    ADD COLUMN COUNT_DUST_COLLECTOR INT,
    ADD COLUMN TYPE_COMPRESSOR VARCHAR(80)
