spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  jpa:
#    show-sql: false
#    hibernate:
#      ddl-auto: none
#    #      use-new-id-generator-mappings: true
#    properties:
#      hibernate:
#        format_sql: true
#    generate-ddl: false

#  liquibase:
#    change-log: 'db/changelog/db.changelog-master.xml'
#    enabled: true


  datasource:
    url: "jdbc:postgresql://localhost:5432/technic"
    #    ?createDatabaseIfNotExist=true
    username: "shuffle"
    password: "shuffle"
#storage:
#  location: './storage'

server:
  port: 8093