insert into TECHNIC (TITLE, MANUFACTURE_COUNTRY, MANUFACTURE, ORDER_ON, CREDIT, TYPE_TECHNIC)
values ('Омар', 'RU', 'ВегаNew', 'AVAILABLE', 'NOT_AVAILABLE', 'VACUUM_CLEANER'),
       ('LG', 'China', 'LGNew', 'AVAILABLE', 'NOT_AVAILABLE', 'VACUUM_CLEANER'),
       ('Пылесос', 'China', 'New', 'AVAILABLE', 'NOT_AVAILABLE', 'VACUUM_CLEANER'),
       ('Plus', 'USA', 'Minus', 'NOT_AVAILABLE', 'AVAILABLE', 'FRIDGE'),
       ('Honor', 'China', 'Honor', 'AVAILABLE', 'NOT_AVAILABLE', 'FRIDGE'),
       ('Холодильник', 'China', 'Холод', 'AVAILABLE', 'NOT_AVAILABLE', 'FRIDGE'),
       ('Iphone', 'USA', 'XXOld', 'AVAILABLE', 'AVAILABLE', 'TV'),
       ('LG_N', 'China', 'LG_Old', 'AVAILABLE', 'NOT_AVAILABLE', 'TV'),
       ('ТВ', 'RUS', 'LG_Old', 'AVAILABLE', 'NOT_AVAILABLE', 'TV'),
       ('Plus_N', 'USA', 'Minus', 'NOT_AVAILABLE', 'AVAILABLE', 'PC'),
       ('Honor_Old', 'China', 'Honor_Old', 'AVAILABLE', 'NOT_AVAILABLE', 'PC'),
       ('ПК', 'China', 'Honor_Old', 'AVAILABLE', 'NOT_AVAILABLE', 'PC'),
       ('Iphone_N', 'USA', 'XXOld_Old', 'AVAILABLE', 'AVAILABLE', 'SMARTPHONE'),
       ('Смартфон', 'USA', 'XXOld_Old', 'AVAILABLE', 'AVAILABLE', 'SMARTPHONE'),
       ('Sony', 'Japan', 'SONYNew', 'AVAILABLE', 'AVAILABLE', 'SMARTPHONE');