
CREATE TABLE IF NOT EXISTS TECHNIC (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    TITLE VARCHAR(80) NOT NULL,
    MANUFACTURE_COUNTRY VARCHAR(80) NOT NULL,
    MANUFACTURE VARCHAR(80) NOT NULL,
    ORDER_ON VARCHAR(80) NOT NULL,
    CREDIT VARCHAR(80) NOT NULL,
    TYPE_TECHNIC VARCHAR(80) NOT NULL
);